import { link } from 'fs'
import BuildProjectMarquee from './BuildProjectMarquee'
import TeslaProjectCodeReport from './TeslaProjectCodeReport'

export default function ApplySection() {
	const sectionInfo = {
		sectionOrder: 2,
		sectionTitle: 'Apply',
		sectionHeader: 'Powerful IDE with AI Tooling',
		sectionSubHeader: `Become a better programmer by building tons of real-world projects and keep
        improving with detailed feedback on your code - generated by state-of-the-art AI.`,
		subsection: [
			{
				icon: PracticeProject,
				title: 'Practice 100+ Projects',
				description: `Improve you skills by building. Choose from over 100+ projects to
                practice, build for your resume and showcase to the world.`
			},
			{
				icon: UnlimitedFeedback,
				title: 'Unlimited building and feedback',
				description: `For every great project you build, we help you make it better with CodeReport™. Get detailed feedback on your projects.`
			},
			{
				icon: BrushAwayBugs,
				title: 'Brush away all the bugs',
				description: `Use code brushes in playgrounds to fix, debug, refactor or even write
                full code blocks - at a click of a button`
			}
		]
	}

	const playgroundLinks = [
		{
			icon: ReactIcon,
			title: 'Boot a React playground'
		},
		{
			icon: HTMLIcon,
			title: 'Boot a HTML playground'
		},
		{
			icon: JavaIcon,
			title: 'Boot a Java playground'
		},
		{
			icon: NodeJSIcon,
			title: 'Boot a Node playground'
		},
		{
			icon: PythonIcon,
			title: 'Boot a Python playground'
		},
		{
			icon: SolidityIcon,
			title: 'Boot a Solidity playground'
		},
		{
			icon: RustIcon,
			title: 'Boot a Rust playground'
		},

		{
			icon: CppIcon,
			title: 'Boot a C++ playground'
		}
	]
	return (
		<div className="w-full flex flex-col items-center">
			<div className="h-24 w-px bg-gradient-to-b from-transparent via-sky-500/60 to-cyan-400 lg:bg-gradient-to-b lg:from-sky-500 lg:to-cyan-400 "></div>
			<span className="h-10 w-10 rounded-full bg-gradient-to-r from-sky-500 to-cyan-400 text-xl text-white font-bold flex justify-center items-center">
				{sectionInfo.sectionOrder}
			</span>
			<span className="uppercase text-[28px] tracking-tight leading-9 font-bold text-transparent bg-gradient-to-b from-sky-600 via-sky-500 to-cyan-400 bg-clip-text pt-6 backdrop-blur-lg bg-white bg-opacity-50">
				{sectionInfo.sectionTitle}
			</span>
			<h2 className="sm:text-6xl lg:text-6xl text-4xl tracking-tighter text-center font-bold text-gray-800 backdrop-blur-lg bg-white bg-opacity-50 p-4">
				{sectionInfo.sectionHeader}
			</h2>
			<span className="text-xl max-w-3xl font-normal leading-8 tracking-tight text-center text-gray-600 my-2 backdrop-blur-lg bg-white bg-opacity-50 px-6">
				{sectionInfo.sectionSubHeader}
			</span>
			<div className="flex flex-col items-center w-full lg:justify-center lg:flex-row py-10 md:py-20 max-w-screen-xl">
				<TeslaProjectCodeReport />
				<div className="relative w-full flex flex-col items-center lg:w-3/6 h-full px-10 sm:px-12 pb-8 xl:px-16 lg:py-16">
					{sectionInfo.subsection.map((item, index) => (
						<div
							key={`subsection-item-${index}`}
							className="pt-6 pb-9 lg:pr-4 max-w-xl  flex flex-col items-center text-center lg:items-start lg:text-left backdrop-blur-lg bg-white bg-opacity-50"
						>
							<item.icon />
							<h3 className="text-[26px] font-semibold text-gray-900 tracking-tight mt-3">
								{item.title}
							</h3>
							<p className="text-base font-normal leading-[26px] text-zinc-700 mt-1">
								{item.description}
							</p>
						</div>
					))}
				</div>
			</div>
			<BuildProjectMarquee />
			<span className="uppercase tracking-widest text-sm text-center sm:text-base font-bold text-gray-500 mb-4backdrop-blur-lg bg-white bg-opacity-50 px-4">
				Boot playgrounds with over 25+ templates
			</span>
			<div className="w-full h-fit flex justify-center mb-20 flex-wrap">
				<div className="flex mt-8 backdrop-blur-lg bg-white bg-opacity-50">
					{playgroundLinks
						.filter((link, index) => index < 4)
						.map((link, index) => (
							<a key={`link-${index}`} title={link.title}>
								<link.icon />
							</a>
						))}
				</div>
				<div className="flex mt-8 backdrop-blur-lg bg-white bg-opacity-50">
					{playgroundLinks
						.filter((link, index) => index >= 4)
						.map((link, index) => (
							<a key={`link-${index}`} title={link.title}>
								<link.icon />
							</a>
						))}
				</div>
			</div>
		</div>
	)
}

function PracticeProject() {
	return (
		<svg
			stroke="currentColor"
			fill="url(#ApplySvgGradient)"
			strokeWidth="0"
			viewBox="0 0 16 16"
			className="h-8 w-8"
			height="1em"
			width="1em"
			xmlns="http://www.w3.org/2000/svg"
		>
			<path d="M4.5 6a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1ZM6 6a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1Zm2-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"></path>
			<path d="M12 1a2 2 0 0 1 2 2 2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2 2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h10ZM2 12V5a2 2 0 0 1 2-2h9a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1Zm1-4v5a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V8H3Zm12-1V5a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v2h12Z"></path>
		</svg>
	)
}
function UnlimitedFeedback() {
	return (
		<svg
			stroke="currentColor"
			fill="url(#ApplySvgGradient)"
			strokeWidth="0"
			viewBox="0 0 16 16"
			className="h-8 w-8"
			height="1em"
			width="1em"
			xmlns="http://www.w3.org/2000/svg"
		>
			<path d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"></path>
			<path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"></path>
		</svg>
	)
}
function BrushAwayBugs() {
	return (
		<svg
			stroke="currentColor"
			fill="url(#ApplySvgGradient)"
			strokeWidth="0"
			viewBox="0 0 16 16"
			className="h-8 w-9"
			height="1em"
			width="1em"
			xmlns="http://www.w3.org/2000/svg"
		>
			<path d="M2 3a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h5.5a.5.5 0 0 1 0 1H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v4a.5.5 0 0 1-1 0V4a1 1 0 0 0-1-1H2Z"></path>
			<path d="M3.146 5.146a.5.5 0 0 1 .708 0L5.177 6.47a.75.75 0 0 1 0 1.06L3.854 8.854a.5.5 0 1 1-.708-.708L4.293 7 3.146 5.854a.5.5 0 0 1 0-.708ZM5.5 9a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5ZM16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-4.854-1.354a.5.5 0 0 0 0 .708l.647.646-.647.646a.5.5 0 0 0 .708.708l.646-.647.646.647a.5.5 0 0 0 .708-.708l-.647-.646.647-.646a.5.5 0 0 0-.708-.708l-.646.647-.646-.647a.5.5 0 0 0-.708 0Z"></path>
		</svg>
	)
}

function ReactIcon() {
	return (
		<svg
			fill="none"
			className="transition-transform hover:scale-110 mx-3.5"
			height={44}
			width={46}
			viewBox="-10.5 -9.4 21 18.9"
		>
			<circle r="2" fill="#00D8FF"></circle>
			<g stroke="#00D8FF">
				<ellipse rx="10" ry="4.5"></ellipse>
				<ellipse rx="10" ry="4.5" transform="rotate(60)"></ellipse>
				<ellipse rx="10" ry="4.5" transform="rotate(120)"></ellipse>
			</g>
		</svg>
	)
}
function HTMLIcon() {
	return (
		<svg
			fill="none"
			viewBox="0 0 400 400"
			height={44}
			width={48}
			className="transition-transform hover:scale-110 mx-3.5"
		>
			<path fill="#E44D26" d="M56 360 24 0h353l-32 360-145 40"></path>
			<path fill="#F16529" d="M200 369V30h145l-28 307"></path>
			<path
				fill="#EBEBEB"
				d="M90 74h110v44h-62l4 45h58v44h-98L90 74Zm14 155h44l3 35 49 14v46l-90-26"
			></path>
			<path
				fill="#fff"
				d="M311 74H200v44h107l4-44Zm-8 89H200v44h55l-6 57-49 14v46l91-26"
			></path>
		</svg>
	)
}
function JavaIcon() {
	return (
		<svg
			className="transition-transform hover:scale-110 mx-3.5"
			fill="none"
			height={44}
			width={48}
			viewBox="0 0 400 400"
		>
			<path
				fill="#5382A1"
				d="M147 309s-15 9 11 12c32 4 48 3 83-3l22 10c-79 34-177-1-116-19Zm-10-43s-17 12 9 15c34 3 61 4 107-5 0 0 7 6 17 10-95 28-200 2-133-20Z"
			></path>
			<path
				fill="#E76F00"
				d="M218 191c19 22-5 42-5 42s49-25 27-56c-21-30-38-45 50-95 0 0-137 34-72 109Z"
			></path>
			<path
				fill="#5382A1"
				d="M322 342s11 9-13 16c-45 14-188 18-228 1-14-6 13-15 21-17 9-2 14-1 14-1-16-12-102 22-44 31 160 26 291-12 250-30ZM154 220s-72 17-25 24c19 2 59 2 96-1l60-8s-11 4-18 10c-74 19-217 10-176-10 35-17 63-15 63-15Zm131 73c75-39 40-76 16-71l-9 2 7-5c48-17 84 50-16 76l2-2Z"
			></path>
			<path
				fill="#E76F00"
				d="M240 0s41 42-40 106c-65 51-15 80 0 113-38-34-66-64-47-92 27-41 103-61 87-127Z"
			></path>
			<path
				fill="#5382A1"
				d="M162 399c72 4 182-3 185-37 0 0-5 13-60 23-61 12-137 11-182 3 0 0 9 8 57 11Z"
			></path>
		</svg>
	)
}
function NodeJSIcon() {
	return (
		<svg
			fill="none"
			viewBox="0 0 400 400"
			height={44}
			width={48}
			className="transition-transform hover:scale-110 mx-3.5"
		>
			<path
				fill="#539E43"
				d="M200 400c-5 0-10-1-15-4l-49-29c-7-4-3-6-1-6l22-10h3l38 23h4l147-85 2-4V115l-2-4-147-84h-4L51 111l-2 4v170l2 4 40 23c22 11 36-2 36-15V130c0-2 1-5 4-5h19c2 0 4 2 4 5v167c0 29-16 46-43 46-9 0-15 0-34-9l-39-22c-9-6-15-16-15-27V116c0-11 6-22 15-27L185 4c9-5 22-5 31 0l147 85c9 5 15 16 15 27v169c0 11-6 21-15 27l-147 85c-5 2-10 3-16 3Zm46-116c-65 0-78-30-78-55 0-2 2-4 5-4h19c2 0 4 1 4 3 3 20 11 29 50 29 31 0 44-7 44-23 0-10-4-17-52-21-40-4-65-13-65-45 0-30 25-48 67-48 47 0 70 17 73 52l-1 3-3 2h-19c-2 0-4-2-4-4-4-20-16-27-46-27-34 0-38 12-38 21 0 11 5 14 51 20 45 6 66 14 66 46s-27 51-73 51Z"
			></path>
		</svg>
	)
}
function PythonIcon() {
	return (
		<svg
			className="transition-transform hover:scale-110 mx-3.5"
			fill="none"
			height={44}
			width={48}
			viewBox="0 0 400 400"
		>
			<path
				fill="url(#a)"
				d="M199 1c-102 0-96 44-96 44v46h97v13H65S0 97 0 199c0 103 57 99 57 99h34v-47s-2-57 55-57h96s54 1 54-52V54s9-53-97-53Zm-54 31a17 17 0 1 1 0 35 17 17 0 0 1 0-35Z"
			></path>
			<path
				fill="url(#b)"
				d="M201 399c102 0 96-44 96-44v-46h-97v-13h135s65 7 65-96c0-102-57-98-57-98h-34v47s2 57-55 57h-96s-54-1-54 52v88s-9 53 97 53Zm54-31a17 17 0 1 1 0-35 17 17 0 0 1 0 35Z"
			></path>
			<defs>
				<linearGradient
					id="a"
					x1="38.4"
					x2="236.7"
					y1="36.8"
					y2="233"
					gradientUnits="userSpaceOnUse"
				>
					<stop stopColor="#387EB8"></stop>
					<stop offset="1" stopColor="#366994"></stop>
				</linearGradient>
				<linearGradient
					id="b"
					x1="160.1"
					x2="373"
					y1="162.8"
					y2="364"
					gradientUnits="userSpaceOnUse"
				>
					<stop stopColor="#FFE052"></stop>
					<stop offset="1" stopColor="#FFC331"></stop>
				</linearGradient>
			</defs>
		</svg>
	)
}
function SolidityIcon() {
	return (
		<svg
			fill="none"
			viewBox="0 0 400 400"
			height={44}
			width={48}
			className="transition-transform hover:scale-110 mx-3.5"
		>
			<path fill="#000" d="m264 0-64 114H71L135 0h129" opacity=".5"></path>
			<path fill="#000" d="M200 114h128L264 0H135l65 114Z" opacity=".6"></path>
			<path fill="#000" d="m135 229 65-115L135 0 71 114l64 115Z" opacity=".8"></path>
			<path fill="#000" d="m136 400 64-114h129l-65 114H136Z" opacity=".5"></path>
			<path fill="#000" d="M200 286H72l64 114h128l-64-114Z" opacity=".6"></path>
			<path fill="#000" d="m264 171-64 115 64 114 65-114-65-115Z" opacity=".8"></path>
		</svg>
	)
}
function RustIcon() {
	return (
		<svg
			className="transition-transform hover:scale-110 mx-3.5"
			fill="none"
			height={44}
			width={48}
			viewBox="0 0 400 400"
		>
			<path
				fill="#000"
				d="m397 195-17-10v-5l14-14a6 6 0 0 0-1-9l-19-7-1-5 11-16a6 6 0 0 0-4-9l-19-3-2-5 8-17a6 6 0 0 0-6-9l-19 1-4-4 5-19a6 6 0 0 0-7-7l-19 5-4-4 1-19a6 6 0 0 0-8-6l-18 8-5-2-3-19a6 6 0 0 0-9-4l-16 11-5-1-7-19a6 6 0 0 0-9-1l-14 14h-5L205 3a6 6 0 0 0-10 0l-10 17h-5L166 6a6 6 0 0 0-9 1l-7 19-5 1-16-11a6 6 0 0 0-9 4l-3 19-5 2-18-8a6 6 0 0 0-8 6l1 19-4 4-19-5a6 6 0 0 0-7 7l5 19-4 4-19-1c-2 0-4 1-5 3s-2 4-1 6l8 17-2 5-19 3a6 6 0 0 0-4 9l11 16-1 5-19 7a6 6 0 0 0-1 9l14 14v5L3 195a6 6 0 0 0 0 10l17 10v5L6 234a6 6 0 0 0 1 9l19 7 1 5-11 16a6 6 0 0 0 4 9l19 3 2 5-8 18a6 6 0 0 0 6 8l19-1 4 4-5 19a6 6 0 0 0 7 7l19-5 4 4-1 19a6 6 0 0 0 8 6l18-8 5 2 3 19a6 6 0 0 0 9 4l16-11 5 1 7 19a6 6 0 0 0 9 1l14-14h5l10 17a6 6 0 0 0 10 0l10-17h5l14 14a6 6 0 0 0 9-1l7-19 5-1 16 11a6 6 0 0 0 9-4l3-19 5-2 18 8a6 6 0 0 0 8-6l-1-19 4-4 19 5a6 6 0 0 0 7-7l-5-19 4-4 19 1a6 6 0 0 0 6-8l-8-18 2-5 19-3a6 6 0 0 0 4-9l-11-16 1-5 19-7a6 6 0 0 0 1-9l-14-14v-5l17-10a6 6 0 0 0 0-10ZM285 334a12 12 0 1 1 5-23 12 12 0 0 1-5 23Zm-6-38c-6-1-11 2-13 8l-6 28a146 146 0 0 1-122-1l-6-27c-1-6-7-10-12-9l-25 5-13-14h120l2-2v-42l-2-2h-35v-26h38c3 0 18 0 23 20l7 31c2 7 11 21 21 21h60l2-1-14 16-25-5Zm-165 38a12 12 0 1 1-5-23 12 12 0 0 1 5 23ZM69 150a12 12 0 1 1-22 10 12 12 0 0 1 22-10Zm-14 33 25-11c6-3 8-9 6-15l-6-12h21v94H59a146 146 0 0 1-4-56Zm112-9v-28h49c3 0 18 3 18 15 0 9-12 13-21 13h-46Zm179 25v11h-15c-2 0-2 1-2 2v7c0 16-9 20-17 21-8 0-17-4-18-8-4-26-12-31-23-40 14-10 30-23 30-42 0-20-14-32-23-39-13-8-28-10-32-10H91c21-23 50-40 82-46l18 19c4 5 11 5 15 1l21-20c43 8 79 35 100 71l-14 32c-2 5 0 12 6 14l27 12v15ZM191 39a12 12 0 1 1 17 17 12 12 0 1 1-17-17Zm139 112a12 12 0 1 1 22 9 12 12 0 1 1-22-9Z"
			></path>
		</svg>
	)
}
function CppIcon() {
	return (
		<svg
			className="transition-transform hover:scale-110 mx-3.5"
			fill="none"
			height={44}
			width={48}
			viewBox="0 0 400 400"
		>
			<path
				fill="#649AD2"
				d="M378 118c0-7-2-13-4-18-3-5-8-9-13-13L218 5c-12-7-25-7-37 1L39 87c-11 7-17 17-17 31v164c0 7 1 13 4 18s7 9 13 13l142 81c12 8 25 8 37 1l143-82c6-4 10-8 13-13s4-11 4-18V118Z"
			></path>
			<path
				fill="#004482"
				d="M200 199 26 300c3 5 7 9 13 13l142 81c12 8 25 8 37 1l143-82c6-4 10-8 13-13L200 199Z"
			></path>
			<path fill="#1A4674" d="M149 229a59 59 0 0 0 102 0l-51-30-51 30Z"></path>
			<path
				fill="#01589C"
				d="M378 118c0-7-2-13-4-18l-174 99 174 101c3-5 4-11 4-18V118Z"
			></path>
			<path
				fill="#fff"
				d="M368 207h-13v13h-14v-13h-13v-14h13v-13h14v13h13v14ZM200 82c43 0 81 23 102 58v1l-51 29a59 59 0 1 0 0 59l52 30A118 118 0 1 1 200 82Zm105 98v13h14v14h-14v13h-13v-13h-14v-14h14v-13h13Z"
			></path>
		</svg>
	)
}
